### ISSUE TITLE
GNoT on Amazon AWS?

### ISSUE THREAD

**Issue by bmasch** [garthee/gnot#2]
I am trying to get this going on Ubuntu running on AWS (t2.micro instance type). Port 5000 is open for TCP. There is both an internal IP address and an external one. In setting up the .gnot_config, I initially used the external IP for "web_host". Upon start with ./web_server.py, the following was output to the terminal via stderr:
- Running on http://54.183.80.198:5000/
  Traceback (most recent call last):
  File "./web_server.py", line 178, in <module>
    run_simple(app.config['web_host'], app.config['web_port'], app, use_debugger=True, use_reloader=True, threaded=True)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 706, in run_simple
    test_socket.bind((hostname, port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
  socket.error: [Errno 99] Cannot assign requested address

I substituted the internal IP for the external, and the stderr changed to:
- Running on http://172.30.0.186:5000/
- Restarting with reloader

There was still no response when hitting http://52.183.80.198:5000 or http://52.183.80.198:5000/index.html with a browser, and no additional output to stderr.

**Comment by garthee** [comment]
The easiest way to handle is to do a local forward.

In your ~/.ssh/config, add something like this to forward port 5000. Edit the details as you need.
<pre><code>
Host myaws
    Hostname 54.183.80.198
    IdentityFile ~/.ssh/id_rsa
    User ubuntu
    LocalForward *:5000 localhost:5000
</code></pre>
Then ssh to your machine by <code>ssh myaws</code>. Now edit ~/.gnot_config to 
<pre><code>
 "web_host":"localhost", 
 "web_port": 5000
</code></pre>
You can access the page from your browser via localhost:5000

If you are accessing without localforward, set ~/.gnot_config to 
<pre><code>
 "web_host":"54.183.80.198", 
 "web_port": 5000
</code></pre>
Make sure that port is not taken by <code>fuser -v -n tcp 5000</code>. You will also need open the port to allow incoming traffic. More details here:
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/authorizing-access-to-an-instance.html

**Comment by bmasch** [comment]
I'm confused by some of that. One problem (or just annoyance) is that the
IP address is not permanent; if I shut the server down (not terminate), I
get a new one and the configs get to be edited. Eventually not a problem.

I'm obviously accessing the instance via ssh from home. I have a Windows7
box, but I use a virtual Linux machine to talk to Amazon.  What do you mean
by "ssh to my machine by ssh myaws"?

Are you suggesting the edit of ~/.ssh/config on my local client or on the
Amazon instance?

If the server is running correctly, I should be able to access it at
54.183.80.198:5000 (at least until the IPaddress changes...). Right now,
there is no answer, even though port 5000 is open. I know that I can get in
via other ports (e.g. 5432 to get to Postgresql remotely, and obviously
port 21 for ssh)

With the web_host set to the Amazon internal IP, I get not error message on
startup. I'm not sure why the internals would have to know about the
external IP.

**Comment by bmasch** [comment]
I'm confused by some of that. One problem (or just annoyance) is that the IP address is not permanent; if I shut the server down (not terminate), I get a new one and the configs get to be edited. Eventually not a problem.

I'm obviously accessing the instance via ssh from home. I have a Windows7 box, but I use a virtual Linux machine to talk to Amazon.  What do you mean by "ssh to my machine by ssh myaws"?

Are you suggesting the edit of ~/.ssh/config on my local client or on the Amazon instance?

If the server is running correctly, I should be able to access it at 54.183.80.198:5000 (at least until the IPaddress changes...). Right now, there is no answer, even though port 5000 is open. I know that I can get in via other ports (e.g. 5432 to get to Postgresql remotely, and obviously port 21 for ssh)

With the web_host set to the Amazon internal IP, I get not error message on startup. I'm not sure why the internals would have to know about the external IP.

**Comment by garthee** [comment]
Method 1: Yes, add that entry to your local ~/.ssh/config. So that when you go to localhost:5000, it will forward all the requests to your aws instance (and make it appear as localhost there). You can do that in your virtual linux os, ssh from the linux terminal, and access via a browser inside linux os. It is the easiest, so that you don't have to worry about firewall or other issues.

Method2: If you are sure that your firewall is open (listening to port 5000) [1], try listening to all ips in GNoT by setting the web_host to 0.0.0.0 [2].

[1] http://www.tixati.com/optimize/open-ports-linux.html
[2] http://stackoverflow.com/questions/19235052/werkzeug-wsgi-only-reachable-via-localhost

**Comment by garthee** [comment]
Since you got it working (I can access it [1]), I  am closing this issue.

[1] http://54.183.80.198:5000/render?submit=SUBMIT&query=module%3A+explore+table%3A+public.obs+field%3A+%22*%22

**Comment by bmasch** [comment]
Thanks, but what seemed to work was putting the Amazon internal IP back in for web_host as well as setting debug=False in the web_server.py (to get around [2]).  

Perhaps part of the confusion is that I was testing a a URL such as http://52.183.80.198:5000/, as I saw an index.html file in the static directory. Perhaps you could add something on the howto about a default URL (if any). 
Was there a separate query you used to identify the obs table?

**Comment by bmasch** [comment]
See my response. I don't understand everything, but this is still amazing.

What might also be useful (to me and others) is something about the
architecture of the demo. Admittedly, I am not that familiar with python
back ends. Where is the dataset (transferred to browser) limited to 1000
records (and is that random or just off the top)? I know there are about
1.5M records.

Thanks much,

Brian

**Comment by garthee** [comment]
1. Interesting. I believe web_host 0.0.0.0 should work as well.
2. You don't open individual html files, they are used to generate the content when called by a module.
3. Default url is your host url (http://54.183.80.198:5000/), there you start making your choices, a) module, b) table, c) fields, and so on. They are autocompleted (based on the db_scope you set in .gnot_config). Further, available options are based on your previous choices. For instance, if you choose explore_calendar, you will see xField as a parameter to choose. Also available fields are based on your choice for table. In fact, you can choose multiple tables, and join them via where clause as well.
4. Individual modules assume default values for parameters. This is to make it easy to start with visualizations, as well as to safe guard against undesirable effects (loading more than 2000 points in your browser for explore module is not advisable). For explore module, limit is set to 1000, such that by default it selects only 1000 entries. But you can pass a different limit, as well as a different ordering by passing a randomization (e.g. random() < 0.1) for where clause. A quick overview of your db can be visualized via [1]
5. Play with the examples [2], to see different modules and available options.

[1] http://54.183.80.198:5000/render?submit=SUBMIT&query=module%3A+explore_relation
[2] http://ddmg1.csail.mit.edu:5000/render?submit=submit&query=module%3A+explore_examples
